name: DB CI (Chicago Taxi)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-db:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: companydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create DB user matching .env.example
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "CREATE USER IF NOT EXISTS 'automation'@'%' IDENTIFIED BY 'pass'; GRANT ALL PRIVILEGES ON companydb.* TO 'automation'@'%'; FLUSH PRIVILEGES;"

      - name: Prepare .env
        run: |
          cp .env.example .env
          sed -i 's/MYSQL_HOST=.*/MYSQL_HOST=127.0.0.1/' .env

      - name: Run migrations (001..005)
        run: python scripts/run_migrations.py

      - name: Load sample data (idempotent)
        run: python scripts/load_trips_chicago.py --sample

      - name: Assert schema
        run: mysql -h127.0.0.1 -uautomation -ppass companydb < sql/tests/001_assert_schema.sql

      - name: Verify counts
        run: python scripts/verify_counts.py --expect-min 1
